services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  mysqldb:
    image: mysql
  
  distributedcache:
    image: redis

  orderdb:
    image: mysql

  messagebroker:
    image: rabbitmq:management
  
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/CatalogAPI/Dockerfile
  
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
  
  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering/OrderingAPI/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  mysql_data:
  orderdb_data:
