services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  mysqldb:
    image: mysql
  
  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server
  
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/CatalogAPI/Dockerfile
  
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/BasketAPI/Dockerfile
  
  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  mysql_data:
